version: '3'

services:
    # backend (Nestjs)
    backend:
        container_name: backend
        tty: true
        build: 
            context: .
            dockerfile: Dockerfile

        volumes:
            - .:/usr/src/app

        init: true

        command:
            [
                'sh',
                '-c',
                'npm i && npx prisma db push --force-reset && npx prisma db seed && npx prisma studio
                | npm run start:dev',
            ]
        environment:
            - DATABASE_URL=${DATABASE_URL}
            - PORT=${PORT}
            - BASE_URL=${BASE_URL}

        networks:
            - backend_db_net

        ports:
            - 5555:5555
            - 8000:8000

        depends_on:
            - db

        restart: on-failure

    # Database (Postgres)
    db:
        container_name: db

        image: postgres:16

        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}

        volumes:
            - db-data:/var/lib/postgresql/data

        networks:
            - backend_db_net

        restart: unless-stopped

networks:
    backend_db_net:

volumes:
    db-data: